version: "3.8"

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: ticket_tracker
            POSTGRES_USER_FILE: /run/secrets/db_user
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        volumes:
            - /mnt/volume_tor1_01/postgres_data:/var/lib/postgresql
            - /root/ticket-tracker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app_network
        secrets:
            - db_user
            - db_password
        deploy:
            placement:
                constraints:
                    - node.labels.postgres==true

    ticket-tracker-app:
        image: ticket-tracker-api:latest
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: ticket_tracker
            PORT: 3000
        networks:
            - app_network
        secrets:
            - db_user
            - db_password
        deploy:
            replicas: 2

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /opt/ssl:/etc/ssl:ro
        networks:
            - app_network

networks:
    app_network:
        external: true

secrets:
    db_user:
        external: true
    db_password:
        external: true
